### PR TITLE
fix-generate-summary-missing-endpoint-url

### LINKED ISSUE #384: generated scenario summary is missing the baseurl
We have defined baseurl in the @ server decorator in the multiclient scenarios PR.
```
@server(
  "http://localhost:3000/client/structure/{client}",
  "",
  {
    client: string,
  }
)
```
And the expected summary should be something like `/client/structure/{client}/one`, but it's now generated as

```
- Endpoints:
  - `get /one`
  - `get /three`
  - `get /three`
  - `get /one`
  - `get /three`
  - `get /three`
```
We should add baseurl info from the tsp compiler result when generating the summary.

### PR DESCRIPTION
**Pull request by qiaozha**
# Cadl Ranch Contribution Checklist:

- [ ] I have written a [scenario spec](../docs/writing-scenario-spec.md)
- [ ] I have **meaningful** `@scenario` names. Someone can look at the list of scenarios and understand what I'm covering.
- [ ] I have written a [mock API](../docs/writing-mock-apis.md)
- [ ] I have used `@scenarioDoc`s for extra scenario description and to tell people **how to pass** my mock api check.

fixes #384

### CODE REVIEW

File: packages/cadl-ranch-expect/src/decorators.ts [hunk 1]
```diff
@@ -133,8 +133,20 @@ function getRouteSegments(program: Program, target: Operation | Interface | Name
...
+  return (template ? template : "/") + segments.map((x) => (x.startsWith("/") ? x.substring(1) : x)).join("/");
+}
+
+function getHostTemplate(program: Program, namespace?: Namespace): string | undefined {
+  if (namespace === undefined) {
+    return undefined;
+  }
+  const server = getServers(program, namespace);
+  if (server && server.length === 1) {
+    return server[0].url.split("localhost:3000")[1];
```
Comment (timotheeguerin) [inline packages/cadl-ranch-expect/src/decorators.ts:147]:
```suggestion
    return new URL(server[0].url).path
```
Or whatever else is the correct property on the URL object for the entire path
I think that would be more reliable.

Comment (qiaozha) [reply packages/cadl-ranch-expect/src/decorators.ts]: Actually we can't, there's a case like `{endpoint}//server/path/multiple/{apiVersion}` and if we use URL, it will report invalid url errors.

Comment (timotheeguerin) [reply packages/cadl-ranch-expect/src/decorators.ts]: hhm right, could maybe catch the error and then keep the entire server url

File: packages/cadl-ranch-expect/src/decorators.ts [hunk 2]
```diff
@@ -133,8 +133,26 @@ function getRouteSegments(program: Program, target: Operation | Interface | Name
...
+  const server = getServers(program, namespace);
+  if (server && server.length === 1) {
+    if (server[0].url.indexOf("localhost:3000") > -1) {
+      return server[0].url.split("localhost:3000")[1];
+    } else if (server[0].url.indexOf("{endpoint}") > -1) {
+      return server[0].url.split("{endpoint}")[1];
+    } else {
+      return server[0].url;
+    }
+  }
```
Comment (qiaozha) [inline packages/cadl-ranch-expect/src/decorators.ts:154]: I am changing it this way.

Comment (qiaozha) [reply packages/cadl-ranch-expect/src/decorators.ts:154]: @timotheeguerin one reason I kind of don't like URL is, it automatically encoding something 
image

Comment (qiaozha) [reply packages/cadl-ranch-expect/src/decorators.ts:154]: The above is the result I get after I change the code like 
```typescript
  if (server && server.length === 1) {
    try {
      return new URL(server[0].url).pathname;
    } catch (e) {
      if (server[0].url.indexOf("{endpoint}") > -1) {
        return server[0].url.split("{endpoint}")[1];
      } else {
        return server[0].url;
      }
    }
  }
```

Comment (weidongxu-microsoft) [reply packages/cadl-ranch-expect/src/decorators.ts:154]: 1. It is not actually "host". Seems more like `getRouteSegmentFromServer`?
2. Hope there is more generic solution for `localhost:3000` and `{endpoint}`, but I don't have good solution. Maybe remove URL scheme and start with first `/`, but I guess there will be bug on this as well.

**Review by weidongxu-microsoft — COMMENTED** [review]
Fine by me.

File: packages/cadl-ranch-expect/src/decorators.ts (hunk 2 above)
Comment (timotheeguerin) [reply packages/cadl-ranch-expect/src/decorators.ts:154]: yeah I guess that's ok we can revisit if we get into more cases that don't work out

**Review by timotheeguerin — APPROVED** [review]

File: packages/cadl-ranch-expect/src/decorators.ts (hunk 2 above)
Comment (qiaozha) [reply packages/cadl-ranch-expect/src/decorators.ts:154]: changed the name to getRouteSegmentFromServer.

**Review by weidongxu-microsoft — APPROVED** [review]

**Review by tadelesh — APPROVED** [review]
